import { TasksProps } from "../../../app/types/TaskProps";

export const toDoList: TasksProps = [
  {
    id: "13",
    position: 13,
    name: "Meditar",
    description: "Praticar meditação para relaxar",
    startTime: "21:45",
    endTime: "22:15",
  },
  {
    id: "2",
    position: 2,
    name: "Ir ao ginásio",
    description: "Treino de cardio e musculação",
    startTime: "10:00",
    endTime: "11:30",
  },
  {
    id: "1",
    position: 1,
    name: "Reunião de trabalho",
    description: "Reunião com a equipe de marketing",
    startTime: "8:30",
    endTime: "9:30",
  },
  {
    id: "4",
    position: 4,
    name: "Enviar relatórios",
    description: "Finalizar e enviar relatórios financeiros",
    startTime: "14:00",
    endTime: "15:00",
  },
  {
    id: "3",
    position: 3,
    name: "Almoço de negócios",
    description: "Restaurante italiano no centro",
    startTime: "12:15",
    endTime: "13:45",
  },
  {
    id: "7",
    position: 7,
    name: "Hora de leitura",
    description: "Ler um capítulo do novo livro",
    startTime: "21:30",
    endTime: "22:30",
  },
  {
    id: "8",
    position: 8,
    name: "Assistir a um webinar",
    description: "Webinar sobre inovações tecnológicas",
    startTime: "23:00",
    endTime: "00:30",
  },
  {
    id: "5",
    position: 5,
    name: "Consulta médica",
    description: "Check-up anual",
    startTime: "16:00",
    endTime: "17:00",
  },
  {
    id: "6",
    position: 6,
    name: "Jantar com amigos",
    description: "Restaurante japonês",
    startTime: "19:00",
    endTime: "21:00",
  },
  {
    id: "9",
    position: 9,
    name: "Passear com o cachorro",
    description: "Dar uma volta no parque",
    startTime: "7:00",
    endTime: "7:30",
  },
  {
    id: "10",
    position: 10,
    name: "Fazer compras",
    description: "Comprar mantimentos para a semana",
    startTime: "14:30",
    endTime: "15:30",
  },
  {
    id: "11",
    position: 11,
    name: "Planejar férias",
    description: "Pesquisar destinos e fazer reservas",
    startTime: "16:30",
    endTime: "17:30",
  },
  {
    id: "12",
    position: 12,
    name: "Ligar para os pais",
    description: "Conversar e saber como eles estão",
    startTime: "20:30",
    endTime: "21:00",
  },

  {
    id: "19",
    position: 19,
    name: "Estudar programação",
    description: "Praticar exercícios de TypeScript",
    startTime: "18:30",
    endTime: "19:30",
  },
  {
    id: "16",
    position: 16,
    name: "Ler e-mails",
    description: "Verificar e responder e-mails pendentes",
    startTime: "8:00",
    endTime: "8:30",
  },
  {
    id: "18",
    position: 18,
    name: "Praticar esporte",
    description: "Jogar tênis no clube",
    startTime: "17:15",
    endTime: "18:15",
  },
  {
    id: "20",
    position: 20,
    name: "Preparar jantar",
    description: "Cozinhar uma refeição saudável",
    startTime: "19:15",
    endTime: "20:00",
  },
  {
    id: "14",
    position: 14,
    name: "Tocar violão",
    description: "Praticar novas músicas e acordes",
    startTime: "22:45",
    endTime: "23:45",
  },
  {
    id: "15",
    position: 15,
    name: "Assistir série",
    description: "Ver dois episódios da série favorita",
    startTime: "23:50",
    endTime: "01:20",
  },
  {
    id: "17",
    position: 17,
    name: "Meditar pela manhã",
    description: "Meditação matinal para começar o dia",
    startTime: "6:30",
    endTime: "7:00",
  },
];
